#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <vector>
#include <map>
#include <memory>
#include <set>
#include <bitset>
#include <functional>
#include <utility>
#include <algorithm>
#include <cmath>
#include <iostream>
#include <sstream>
#include <queue>
#include <fstream>
#include <cstdlib>
#include <string>
#include <string_view>
#include <Windows.h>
#include "imgui.h"
#include "imgui_impl_opengl3.h"
#include "imgui_impl_win32.h"