#pragma once

namespace Rogue
{
	enum class SystemID
	{
		id_MEMORYMANAGER = 0,
		id_INPUTMANAGER,
		id_EVENTMANAGER,
		id_WINDOWSYSTEM,
		id_GRAPHICSSYSTEM,
		id_ANIMATIONSYSTEM,
		id_DEBUGDRAWSYSTEM,
		id_CAMERASYSTEM,
		id_FONTSYSTEM,
		id_AUDIOSYSTEM,
		id_PHYSICSSYSTEM,
		id_COLLISIONTAGSYSTEM,
		id_COLLISIONSYSTEM,
		id_BOXCOLLISIONSYSTEM,
		id_CIRCLECOLLISIONSYSTEM,
		id_LOGICSYSTEM,
		id_PLAYERCONTROLLERSYSTEM,
		id_MENUCONTROLLERSYSTEM,
		id_TESTSYSTEM,
		id_EDITOR,
		id_CURSORSYSTEM,
		id_PICKINGSYSTEM,
		id_PARTICLESYSTEM,
		id_PARTICLEEMITTERSYSTEM,
		id_UISYSTEM,

		id_LASTSYS
	};
}